// examples/nextjs/app/sign-up/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { SignUp, SocialButtons, useAuthon } from '@authon/nextjs'

type View = 'builtin' | 'custom'

export default function SignUpPage() {
  const [view, setView] = useState<View>('builtin')

  return (
    <div className="page-centered">
      <div style={{ width: '100%', maxWidth: 500 }}>
        <div style={{ textAlign: 'center', marginBottom: 24 }}>
          <h1 style={{ fontSize: 26, fontWeight: 700, color: 'var(--text-primary)', marginBottom: 8 }}>
            Sign Up Demo
          </h1>
          <p style={{ color: 'var(--text-secondary)', fontSize: 14 }}>
            Two approaches — toggle to compare
          </p>
        </div>

        <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 28 }}>
          <div className="toggle-bar">
            <button
              className={`toggle-btn${view === 'builtin' ? ' active' : ''}`}
              onClick={() => setView('builtin')}
            >
              Built-in Component
            </button>
            <button
              className={`toggle-btn${view === 'custom' ? ' active' : ''}`}
              onClick={() => setView('custom')}
            >
              Custom Form
            </button>
          </div>
        </div>

        {view === 'builtin' ? <BuiltinSignUp /> : <CustomSignUp />}
      </div>
    </div>
  )
}

function BuiltinSignUp() {
  const router = useRouter()

  return (
    <div>
      <div className="card" style={{ marginBottom: 16, padding: '12px 16px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--accent)', background: 'var(--accent-light)', padding: '2px 8px', borderRadius: 5 }}>
            Built-in
          </span>
          <code style={{ fontSize: 12, color: 'var(--text-secondary)' }}>
            {'<SignUp onSignUp={() => router.push("/")} />'}
          </code>
        </div>
      </div>
      <SignUp
        onSignUp={() => router.push('/')}
        onNavigateSignIn={() => router.push('/sign-in')}
      />
    </div>
  )
}

function CustomSignUp() {
  const router = useRouter()
  const { client } = useAuthon()

  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [displayName, setDisplayName] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!client) return

    if (password !== confirmPassword) {
      setError('Passwords do not match')
      return
    }
    if (password.length < 8) {
      setError('Password must be at least 8 characters')
      return
    }

    setLoading(true)
    setError('')
    try {
      await client.signUpWithEmail(email, password, { displayName: displayName || undefined })
      router.push('/')
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Sign up failed')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="card">
      <div style={{ marginBottom: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
          <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--accent-2)', background: 'rgba(79, 70, 229, 0.12)', padding: '2px 8px', borderRadius: 5 }}>
            Custom
          </span>
          <code style={{ fontSize: 12, color: 'var(--text-secondary)' }}>
            client.signUpWithEmail(email, password, meta)
          </code>
        </div>
      </div>

      {error && <div className="alert alert-error" style={{ marginBottom: 16 }}>{error}</div>}

      <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        <div className="form-group">
          <label className="form-label" htmlFor="displayName">Display Name <span style={{ color: 'var(--text-tertiary)' }}>(optional)</span></label>
          <input
            id="displayName"
            className="form-input"
            type="text"
            placeholder="Your name"
            value={displayName}
            onChange={e => setDisplayName(e.target.value)}
            autoComplete="name"
          />
        </div>

        <div className="form-group">
          <label className="form-label" htmlFor="email">Email</label>
          <input
            id="email"
            className="form-input"
            type="email"
            placeholder="you@example.com"
            value={email}
            onChange={e => setEmail(e.target.value)}
            autoComplete="email"
            required
          />
        </div>

        <div className="form-group">
          <label className="form-label" htmlFor="password">Password</label>
          <input
            id="password"
            className="form-input"
            type="password"
            placeholder="Minimum 8 characters"
            value={password}
            onChange={e => setPassword(e.target.value)}
            autoComplete="new-password"
            required
          />
        </div>

        <div className="form-group">
          <label className="form-label" htmlFor="confirmPassword">Confirm Password</label>
          <input
            id="confirmPassword"
            className="form-input"
            type="password"
            placeholder="Repeat your password"
            value={confirmPassword}
            onChange={e => setConfirmPassword(e.target.value)}
            autoComplete="new-password"
            required
          />
        </div>

        <button type="submit" className="btn btn-primary btn-full" disabled={loading}>
          {loading ? <span className="loading-spinner" /> : 'Create account'}
        </button>
      </form>

      <div style={{ display: 'flex', alignItems: 'center', gap: 12, margin: '20px 0' }}>
        <div className="divider" style={{ flex: 1 }} />
        <span style={{ color: 'var(--text-tertiary)', fontSize: 13 }}>or sign up with</span>
        <div className="divider" style={{ flex: 1 }} />
      </div>

      <div>
        <div style={{ fontSize: 12, color: 'var(--text-tertiary)', marginBottom: 10 }}>
          <code style={{ color: 'var(--accent)' }}>{'<SocialButtons />'}</code>
          {' — full-width buttons'}
        </div>
        <SocialButtons
          onSuccess={() => router.push('/')}
          onError={e => setError(e.message)}
        />
      </div>

      <div style={{ marginTop: 20, textAlign: 'center', fontSize: 14, color: 'var(--text-secondary)' }}>
        Already have an account?{' '}
        <Link href="/sign-in" style={{ color: 'var(--accent)', fontWeight: 600 }}>
          Sign in
        </Link>
      </div>
    </div>
  )
}

// examples/vue/src/views/SignUp.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter, RouterLink } from 'vue-router'
import { useAuthon, AuthonSocialButtons } from '@authon/vue'

type View = 'builtin' | 'custom'

const router = useRouter()
const { client, openSignUp } = useAuthon()

const view = ref<View>('builtin')

// Builtin
const builtinLoading = ref(false)
const handleBuiltinSignUp = async () => {
  builtinLoading.value = true
  try {
    await openSignUp()
    router.push('/')
  } finally {
    builtinLoading.value = false
  }
}

// Custom form
const displayName = ref('')
const email = ref('')
const password = ref('')
const confirmPassword = ref('')
const loading = ref(false)
const error = ref('')

const handleSubmit = async () => {
  if (!client) return

  if (password.value !== confirmPassword.value) {
    error.value = 'Passwords do not match'
    return
  }
  if (password.value.length < 8) {
    error.value = 'Password must be at least 8 characters'
    return
  }

  loading.value = true
  error.value = ''
  try {
    await client.signUpWithEmail(email.value, password.value, {
      displayName: displayName.value || undefined,
    })
    router.push('/')
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Sign up failed'
  } finally {
    loading.value = false
  }
}

const handleSocialError = (e: Error) => {
  error.value = e.message
}

const handleSocialSuccess = () => {
  router.push('/')
}
</script>

<template>
  <div class="page-centered">
    <div style="width: 100%; max-width: 500px;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="font-size: 26px; font-weight: 700; color: var(--text-primary); margin-bottom: 8px;">
          Sign Up Demo
        </h1>
        <p style="color: var(--text-secondary); font-size: 14px;">
          Two approaches — toggle to compare
        </p>
      </div>

      <div style="display: flex; justify-content: center; margin-bottom: 28px;">
        <div class="toggle-bar">
          <button :class="['toggle-btn', view === 'builtin' ? 'active' : '']" @click="view = 'builtin'">
            Built-in Component
          </button>
          <button :class="['toggle-btn', view === 'custom' ? 'active' : '']" @click="view = 'custom'">
            Custom Form
          </button>
        </div>
      </div>

      <!-- Built-in -->
      <template v-if="view === 'builtin'">
        <div>
          <div class="card" style="margin-bottom: 16px; padding: 12px 16px;">
            <div style="display: flex; align-items: center; gap: 8px;">
              <span style="font-size: 12px; font-weight: 600; color: var(--accent); background: var(--accent-light); padding: 2px 8px; border-radius: 5px;">
                Built-in
              </span>
              <code style="font-size: 12px; color: var(--text-secondary);">
                openSignUp() — SDK managed popup/redirect
              </code>
            </div>
          </div>
          <div class="card" style="text-align: center; padding: 40px 32px;">
            <div style="font-size: 40px; margin-bottom: 16px;">✨</div>
            <p style="color: var(--text-secondary); font-size: 14px; margin-bottom: 24px;">
              Click below to open the Authon built-in sign-up flow
            </p>
            <button class="btn btn-primary" style="font-size: 15px; padding: 12px 28px;" @click="handleBuiltinSignUp" :disabled="builtinLoading">
              <span v-if="builtinLoading" class="loading-spinner" />
              <span v-else>Open Sign Up</span>
            </button>
            <div style="margin-top: 20px; font-size: 13px; color: var(--text-tertiary);">
              Uses <code style="color: var(--accent);">useAuthon().openSignUp()</code>
            </div>
          </div>
        </div>
      </template>

      <!-- Custom Form -->
      <template v-else>
        <div class="card">
          <div style="margin-bottom: 16px;">
            <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 4px;">
              <span style="font-size: 12px; font-weight: 600; color: var(--accent-2); background: rgba(79, 70, 229, 0.12); padding: 2px 8px; border-radius: 5px;">
                Custom
              </span>
              <code style="font-size: 12px; color: var(--text-secondary);">
                client.signUpWithEmail(email, password, meta)
              </code>
            </div>
          </div>

          <div v-if="error" class="alert alert-error" style="margin-bottom: 16px;">{{ error }}</div>

          <form @submit.prevent="handleSubmit" style="display: flex; flex-direction: column; gap: 16px;">
            <div class="form-group">
              <label class="form-label" for="displayName">
                Display Name
                <span style="color: var(--text-tertiary);">(optional)</span>
              </label>
              <input
                id="displayName"
                class="form-input"
                type="text"
                placeholder="Your name"
                v-model="displayName"
                autocomplete="name"
              />
            </div>

            <div class="form-group">
              <label class="form-label" for="email">Email</label>
              <input
                id="email"
                class="form-input"
                type="email"
                placeholder="you@example.com"
                v-model="email"
                autocomplete="email"
                required
              />
            </div>

            <div class="form-group">
              <label class="form-label" for="password">Password</label>
              <input
                id="password"
                class="form-input"
                type="password"
                placeholder="Minimum 8 characters"
                v-model="password"
                autocomplete="new-password"
                required
              />
            </div>

            <div class="form-group">
              <label class="form-label" for="confirmPassword">Confirm Password</label>
              <input
                id="confirmPassword"
                class="form-input"
                type="password"
                placeholder="Repeat your password"
                v-model="confirmPassword"
                autocomplete="new-password"
                required
              />
            </div>

            <button type="submit" class="btn btn-primary btn-full" :disabled="loading">
              <span v-if="loading" class="loading-spinner" />
              <span v-else>Create account</span>
            </button>
          </form>

          <div style="display: flex; align-items: center; gap: 12px; margin: 20px 0;">
            <div class="divider" style="flex: 1;" />
            <span style="color: var(--text-tertiary); font-size: 13px;">or sign up with</span>
            <div class="divider" style="flex: 1;" />
          </div>

          <div>
            <div style="font-size: 12px; color: var(--text-tertiary); margin-bottom: 10px;">
              <code style="color: var(--accent);">&lt;AuthonSocialButtons /&gt;</code>
              — full-width buttons
            </div>
            <AuthonSocialButtons
              :on-success="handleSocialSuccess"
              :on-error="handleSocialError"
            />
          </div>

          <div style="margin-top: 20px; text-align: center; font-size: 14px; color: var(--text-secondary);">
            Already have an account?
            <RouterLink to="/sign-in" style="color: var(--accent); font-weight: 600;">Sign in</RouterLink>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>
