// examples/react/src/components/ProtectedRoute.tsx
import { useAuthon } from '@authon/react'
import { Navigate, Outlet } from 'react-router-dom'

export default function ProtectedRoute() {
  const { isSignedIn, isLoading } = useAuthon()

  if (isLoading) {
    return (
      <div className="page-centered">
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16 }}>
          <div className="loading-spinner-lg" />
          <p style={{ color: 'var(--text-secondary)', fontSize: 14 }}>Loading...</p>
        </div>
      </div>
    )
  }

  if (!isSignedIn) {
    return <Navigate to="/sign-in" replace />
  }

  return <Outlet />
}

// examples/vue/src/components/ProtectedRoute.vue
<script setup lang="ts">
import { useAuthon } from '@authon/vue'
import { RouterView } from 'vue-router'

const { isSignedIn, isLoading } = useAuthon()
</script>

<template>
  <div v-if="isLoading" class="page-centered">
    <div style="display: flex; flex-direction: column; align-items: center; gap: 16px;">
      <div class="loading-spinner-lg" />
      <p style="color: var(--text-secondary); font-size: 14px;">Loading...</p>
    </div>
  </div>

  <RouterView v-else-if="isSignedIn" />

  <div v-else class="page-centered">
    <p style="color: var(--text-secondary);">Redirecting...</p>
  </div>
</template>
