// examples/vue/src/views/Home.vue
<script setup lang="ts">
import { computed } from 'vue'
import { RouterLink } from 'vue-router'
import { AuthonSignedIn, AuthonSignedOut, useUser } from '@authon/vue'

const { user: userRef } = useUser()
const user = computed(() => userRef.value)

const FEATURES = [
  {
    icon: '🔐',
    title: 'Email & Password Auth',
    desc: 'Full sign-in / sign-up flow with validation and error handling.',
  },
  {
    icon: '🌐',
    title: 'Social Login (10 providers)',
    desc: 'Google, Apple, Kakao, Naver, Facebook, GitHub, Discord, X, LINE, Microsoft.',
  },
  {
    icon: '🛡️',
    title: 'Built-in Components',
    desc: '<AuthonSignIn />, <AuthonSignUp />, <AuthonUserButton /> — drop-in ready.',
  },
  {
    icon: '🔑',
    title: 'Two-Factor Auth (MFA)',
    desc: 'TOTP authenticator app setup with QR code and backup codes.',
  },
  {
    icon: '📱',
    title: 'Session Management',
    desc: 'List all active sessions across devices, revoke any session.',
  },
  {
    icon: '👤',
    title: 'Profile Management',
    desc: 'Update display name, avatar URL, phone number via updateProfile().',
  },
  {
    icon: '🚦',
    title: 'Conditional Rendering',
    desc: '<AuthonSignedIn>, <AuthonSignedOut> — render UI based on auth state.',
  },
  {
    icon: '🪝',
    title: 'Vue Composables',
    desc: 'useAuthon(), useUser() — reactive refs with Vue 3 Composition API.',
  },
]

const initials = computed(() => {
  const u = user.value
  if (!u) return '?'
  if (u.displayName) return u.displayName[0].toUpperCase()
  return (u.email?.[0] ?? '?').toUpperCase()
})

const welcomeName = computed(() => {
  const u = user.value
  if (!u) return ''
  return u.displayName ?? u.email?.split('@')[0] ?? ''
})
</script>

<template>
  <div class="page">
    <div style="text-align: center; padding: 60px 0 48px;">
      <div
        style="
          display: inline-flex;
          align-items: center;
          gap: 8px;
          padding: 6px 16px;
          border-radius: 99px;
          background: var(--accent-light);
          border: 1px solid rgba(124, 58, 237, 0.3);
          font-size: 13px;
          color: var(--accent);
          font-weight: 600;
          margin-bottom: 24px;
        "
      >
        <span>v0.3.0</span>
        <span style="opacity: 0.5;">|</span>
        <span>Reference Implementation</span>
      </div>

      <h1
        style="
          font-size: clamp(32px, 5vw, 56px);
          font-weight: 800;
          line-height: 1.15;
          letter-spacing: -0.03em;
          margin-bottom: 20px;
          background: linear-gradient(135deg, #f1f5f9 0%, #94a3b8 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
        "
      >
        Authon Vue SDK<br />Example App
      </h1>

      <p
        style="
          font-size: 18px;
          color: var(--text-secondary);
          max-width: 560px;
          margin: 0 auto 40px;
          line-height: 1.6;
        "
      >
        Complete authentication flow demo using
        <code
          style="
            color: var(--accent);
            background: var(--accent-light);
            padding: 2px 8px;
            border-radius: 5px;
            font-size: 15px;
          "
        >@authon/vue</code>.
        Every feature of the SDK — demonstrated and ready to copy.
      </p>

      <AuthonSignedOut>
        <div style="display: flex; gap: 12px; justify-content: center; flex-wrap: wrap;">
          <RouterLink
            to="/sign-in"
            class="btn btn-primary"
            style="font-size: 15px; padding: 12px 28px; border-radius: 10px;"
          >
            Sign in
          </RouterLink>
          <RouterLink
            to="/sign-up"
            class="btn btn-secondary"
            style="font-size: 15px; padding: 12px 28px; border-radius: 10px;"
          >
            Create account
          </RouterLink>
        </div>
      </AuthonSignedOut>

      <AuthonSignedIn>
        <div
          style="
            display: inline-flex;
            align-items: center;
            gap: 12px;
            padding: 14px 24px;
            border-radius: 12px;
            background: var(--bg-card);
            border: 1px solid var(--border);
            margin-bottom: 20px;
          "
        >
          <div class="avatar">
            <img v-if="user?.avatarUrl" :src="user.avatarUrl" alt="avatar" />
            <template v-else>{{ initials }}</template>
          </div>
          <div style="text-align: left;">
            <div style="font-weight: 600; color: var(--text-primary);">
              Welcome back, {{ welcomeName }}!
            </div>
            <div style="font-size: 13px; color: var(--text-secondary);">{{ user?.email }}</div>
          </div>
        </div>
        <br />
        <div style="display: flex; gap: 12px; justify-content: center; flex-wrap: wrap;">
          <RouterLink
            to="/profile"
            class="btn btn-primary"
            style="font-size: 15px; padding: 12px 28px; border-radius: 10px;"
          >
            View Profile
          </RouterLink>
          <RouterLink
            to="/mfa"
            class="btn btn-secondary"
            style="font-size: 15px; padding: 12px 28px; border-radius: 10px;"
          >
            MFA Setup
          </RouterLink>
          <RouterLink
            to="/sessions"
            class="btn btn-secondary"
            style="font-size: 15px; padding: 12px 28px; border-radius: 10px;"
          >
            Sessions
          </RouterLink>
        </div>

        <AuthonSignedIn>
          <div v-if="user?.emailVerified" style="margin-top: 16px;">
            <span class="badge badge-success">Email verified</span>
          </div>
          <p v-else style="color: var(--warning); font-size: 13px; margin-top: 16px;">
            Your email is not verified.
          </p>
        </AuthonSignedIn>
      </AuthonSignedIn>
    </div>

    <div style="margin-bottom: 48px;">
      <h2 style="font-size: 22px; font-weight: 700; color: var(--text-primary); margin-bottom: 8px; text-align: center;">
        Features Demonstrated
      </h2>
      <p style="text-align: center; color: var(--text-secondary); font-size: 14px; margin-bottom: 28px;">
        Navigate to each page to see the feature in action
      </p>
      <div class="feature-grid">
        <div v-for="f in FEATURES" :key="f.title" class="feature-card">
          <div class="feature-icon">{{ f.icon }}</div>
          <div class="feature-title">{{ f.title }}</div>
          <div class="feature-desc">{{ f.desc }}</div>
        </div>
      </div>
    </div>

    <div class="card" style="margin-bottom: 48px;">
      <div class="section-title">Quick Start</div>
      <pre
        style="
          background: var(--bg-0);
          border: 1px solid var(--border);
          border-radius: 8px;
          padding: 16px 20px;
          font-size: 13px;
          color: #93c5fd;
          overflow: auto;
          line-height: 1.7;
          font-family: 'Courier New', monospace;
        "
      >import { createAuthon, AuthonSignIn, useAuthon } from '@authon/vue'

const authon = createAuthon({ publishableKey: 'your-project-id' })
app.use(authon)

// In your component:
const { isSignedIn, user, signOut } = useAuthon()</pre>
    </div>
  </div>
</template>

// examples/react/src/pages/Home.tsx
import { Link } from 'react-router-dom'
import { SignedIn, SignedOut, Protect, useUser } from '@authon/react'

const FEATURES = [
  {
    icon: '🔐',
    title: 'Email & Password Auth',
    desc: 'Full sign-in / sign-up flow with validation and error handling.',
  },
  {
    icon: '🌐',
    title: 'Social Login (10 providers)',
    desc: 'Google, Apple, Kakao, Naver, Facebook, GitHub, Discord, X, LINE, Microsoft.',
  },
  {
    icon: '🛡️',
    title: 'Built-in Components',
    desc: '<SignIn />, <SignUp />, <UserButton />, <UserProfile /> — drop-in ready.',
  },
  {
    icon: '🔑',
    title: 'Two-Factor Auth (MFA)',
    desc: 'TOTP authenticator app setup with QR code and backup codes.',
  },
  {
    icon: '📱',
    title: 'Session Management',
    desc: 'List all active sessions across devices, revoke any session.',
  },
  {
    icon: '👤',
    title: 'Profile Management',
    desc: 'Update display name, avatar URL, phone number via updateProfile().',
  },
  {
    icon: '🚦',
    title: 'Conditional Rendering',
    desc: '<SignedIn>, <SignedOut>, <Protect> — render UI based on auth state.',
  },
  {
    icon: '🪝',
    title: 'React Hooks',
    desc: 'useAuthon(), useUser(), useAuthonMfa(), useAuthonSessions().',
  },
]

export default function Home() {
  const { user } = useUser()

  return (
    <div className="page">
      <div style={{ textAlign: 'center', padding: '60px 0 48px' }}>
        <div style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: 8,
          padding: '6px 16px',
          borderRadius: 99,
          background: 'var(--accent-light)',
          border: '1px solid rgba(124, 58, 237, 0.3)',
          fontSize: 13,
          color: 'var(--accent)',
          fontWeight: 600,
          marginBottom: 24,
        }}>
          <span>v0.3.0</span>
          <span style={{ opacity: 0.5 }}>|</span>
          <span>Reference Implementation</span>
        </div>

        <h1 style={{
          fontSize: 'clamp(32px, 5vw, 56px)',
          fontWeight: 800,
          lineHeight: 1.15,
          letterSpacing: '-0.03em',
          marginBottom: 20,
          background: 'linear-gradient(135deg, #f1f5f9 0%, #94a3b8 100%)',
          WebkitBackgroundClip: 'text',
          WebkitTextFillColor: 'transparent',
          backgroundClip: 'text',
        }}>
          Authon React SDK
          <br />Example App
        </h1>

        <p style={{
          fontSize: 18,
          color: 'var(--text-secondary)',
          maxWidth: 560,
          margin: '0 auto 40px',
          lineHeight: 1.6,
        }}>
          Complete authentication flow demo using <code style={{ color: 'var(--accent)', background: 'var(--accent-light)', padding: '2px 8px', borderRadius: 5, fontSize: 15 }}>@authon/react</code>.
          Every feature of the SDK — demonstrated and ready to copy.
        </p>

        <SignedOut>
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link
              to="/sign-in"
              className="btn btn-primary"
              style={{ fontSize: 15, padding: '12px 28px', borderRadius: 10 }}
            >
              Sign in
            </Link>
            <Link
              to="/sign-up"
              className="btn btn-secondary"
              style={{ fontSize: 15, padding: '12px 28px', borderRadius: 10 }}
            >
              Create account
            </Link>
          </div>
        </SignedOut>

        <SignedIn>
          <div style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 12,
            padding: '14px 24px',
            borderRadius: 12,
            background: 'var(--bg-card)',
            border: '1px solid var(--border)',
            marginBottom: 20,
          }}>
            <div className="avatar">
              {user?.avatarUrl ? (
                <img src={user.avatarUrl} alt="avatar" />
              ) : (
                (user?.displayName?.[0] ?? user?.email?.[0] ?? '?').toUpperCase()
              )}
            </div>
            <div style={{ textAlign: 'left' }}>
              <div style={{ fontWeight: 600, color: 'var(--text-primary)' }}>
                Welcome back, {user?.displayName ?? user?.email?.split('@')[0]}!
              </div>
              <div style={{ fontSize: 13, color: 'var(--text-secondary)' }}>{user?.email}</div>
            </div>
          </div>
          <br />
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link to="/profile" className="btn btn-primary" style={{ fontSize: 15, padding: '12px 28px', borderRadius: 10 }}>
              View Profile
            </Link>
            <Link to="/mfa" className="btn btn-secondary" style={{ fontSize: 15, padding: '12px 28px', borderRadius: 10 }}>
              MFA Setup
            </Link>
            <Link to="/sessions" className="btn btn-secondary" style={{ fontSize: 15, padding: '12px 28px', borderRadius: 10 }}>
              Sessions
            </Link>
          </div>
        </SignedIn>

        <Protect
          condition={(u) => !!u?.emailVerified}
          fallback={
            <SignedIn>
              <p style={{ color: 'var(--warning)', fontSize: 13, marginTop: 16 }}>
                Your email is not verified.
              </p>
            </SignedIn>
          }
        >
          <SignedIn>
            <div style={{ marginTop: 16 }}>
              <span className="badge badge-success">Email verified</span>
            </div>
          </SignedIn>
        </Protect>
      </div>

      <div style={{ marginBottom: 48 }}>
        <h2 style={{ fontSize: 22, fontWeight: 700, color: 'var(--text-primary)', marginBottom: 8, textAlign: 'center' }}>
          Features Demonstrated
        </h2>
        <p style={{ textAlign: 'center', color: 'var(--text-secondary)', fontSize: 14, marginBottom: 28 }}>
          Navigate to each page to see the feature in action
        </p>
        <div className="feature-grid">
          {FEATURES.map((f) => (
            <div key={f.title} className="feature-card">
              <div className="feature-icon">{f.icon}</div>
              <div className="feature-title">{f.title}</div>
              <div className="feature-desc">{f.desc}</div>
            </div>
          ))}
        </div>
      </div>

      <div className="card" style={{ marginBottom: 48 }}>
        <div className="section-title">Quick Start</div>
        <pre style={{
          background: 'var(--bg-0)',
          border: '1px solid var(--border)',
          borderRadius: 8,
          padding: '16px 20px',
          fontSize: 13,
          color: '#93c5fd',
          overflow: 'auto',
          lineHeight: 1.7,
          fontFamily: "'Courier New', monospace",
        }}>
{`import { AuthonProvider, SignIn, useAuthon } from '@authon/react'

function App() {
  return (
    <AuthonProvider publishableKey="your-project-id">
      <SignIn onSignIn={() => console.log('signed in!')} />
    </AuthonProvider>
  )
}`}
        </pre>
      </div>
    </div>
  )
}
